### ISSUE TITLE
Fix wrong variable type in "set_max_time_per_frame(const bool value)" and others in the same class

### ISSUE THREAD

**Issue by ozzr** [Relintai/thread_pool#1]
Hi, first of all... you have created really amazing modules!!
I am using this one inside my upcoming terrain module, with some minor modifications. While reading the code I found that some methods to modify float values declare arguments as boolean. I am new in c++,, but is this intended?

**Comment by Relintai** [comment]
Hi,

Thanks for reporting.

No, those are typos, that I never noticed because I never set them from script before.

I'll fix them (probably tomorrow).

I also did some improvements to the module in the pandemonium engine repo which I wanted to backport for a while, I'll probably do that too.

I also think set_max_time_per_frame needs to recalculate some internal variables that I skipped doing back when I implemented it, I'll make sure that that works aswell.

**Comment by ozzr** [comment]
Great!... then.... can I take your improvements from the pandemonium engine and use them? 😇

**Comment by ozzr** [comment]
Ah, by the way... I just downloaded al your modules... I am styding them.

**Comment by Relintai** [comment]
> Great!... then.... can I take your improvements from the pandemonium engine and use them? innocent

That's why its open source.

However note that I moved it to core in that project, and I also had to do a few engine side changes to it to make it work that way, so you can't just copy it's classes back to this module anymore. It also needs a bit more tweaks, and I think it probably still has methods that are affected by this same issue.

I'll likely get to it in a few hours so you will probably want to wait a bit.

By the way I only made internal changes to it, like it now uses a List instead of a Vector, and other smaller fixes, so from your code's point of view nothing will change after I backport it.
